version: '3'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.2
    ports:
      - 3306:3306
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=

  myapp:
    tty: true
    image: simple-laravel-docker
    stdin_open: true
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=
    depends_on:
      - mariadb
    ports:
      - 3000:80
    volumes:
      - ./:/var/www/html
      - /var/cache:/var/cache
